"""empty message

Revision ID: 3f2c5337cbb2
Revises: a2ac26df2418
Create Date: 2021-04-15 14:36:58.811032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2c5337cbb2'
down_revision = 'a2ac26df2418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('loan_duration', sa.Integer(), nullable=False),
    sa.Column('loan_duration_unit', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_duration', 'loan_duration_unit', name='unique_type'),
    sa.UniqueConstraint('name')
    )
    op.add_column('book', sa.Column('book_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'book_type', ['book_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'book_type_id')
    op.drop_table('book_type')
    # ### end Alembic commands ###
