"""empty message

Revision ID: 6696d25858ef
Revises: d08ad70f90f3
Create Date: 2020-11-06 08:45:46.552779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6696d25858ef'
down_revision = 'd08ad70f90f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('original_due_date', sa.Integer(), nullable=True))
    op.drop_constraint('subscriber_phone_key', 'subscriber', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('subscriber_phone_key', 'subscriber', ['phone'])
    op.drop_column('loan', 'original_due_date')
    # ### end Alembic commands ###
