"""empty message

Revision ID: 97a4a3fb3a60
Revises: ace2f2163555
Create Date: 2021-12-14 18:43:16.296578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a4a3fb3a60'
down_revision = 'ace2f2163555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('allow_extend', sa.Boolean(), nullable=True))
    op.add_column('loan', sa.Column('num_extensions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'num_extensions')
    op.drop_column('loan', 'allow_extend')
    # ### end Alembic commands ###
