"""empty message

Revision ID: a2ac26df2418
Revises: 87158c0132f4
Create Date: 2021-04-15 09:00:44.220230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ac26df2418'
down_revision = '87158c0132f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('expired', sa.Boolean(), nullable=True))
    op.execute('UPDATE subscriber SET expired = false')
    op.alter_column('subscriber', 'expired', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'expired')
    # ### end Alembic commands ###
