"""empty message

Revision ID: a924c455c0d0
Revises: 6696d25858ef
Create Date: 2021-01-31 20:58:16.235903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a924c455c0d0'
down_revision = '6696d25858ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_book', 'book', type_='unique')
    op.drop_constraint('loan-book', 'loan', type_='foreignkey')
    op.create_foreign_key(None, 'loan', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.create_foreign_key('loan-book', 'loan', 'book', ['book_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint('unique_book', 'book', ['title', 'author_id'])
    # ### end Alembic commands ###
