"""empty message

Revision ID: ace2f2163555
Revises: d2e795c3ce0e
Create Date: 2021-12-14 15:32:58.030278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace2f2163555'
down_revision = 'd2e795c3ce0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('allow_extend', sa.Boolean(), nullable=True))
    op.add_column('loan', sa.Column('num_extensions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'num_extensions')
    op.drop_column('loan', 'allow_extend')
    # ### end Alembic commands ###
