"""empty message

Revision ID: d08ad70f90f3
Revises: 7ec2358350a0
Create Date: 2020-11-03 21:12:09.213725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08ad70f90f3'
down_revision = '7ec2358350a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('original_due_date', sa.Integer(), nullable=True))
    op.drop_column('loan', 'extended_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('extended_date', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('loan', 'original_due_date')
    # ### end Alembic commands ###
