"""empty message

Revision ID: d2e795c3ce0e
Revises: 09f014e432df
Create Date: 2021-12-14 15:31:34.462985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e795c3ce0e'
down_revision = '09f014e432df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('allow_extend', sa.Boolean(), nullable=False))
    op.add_column('loan', sa.Column('num_extensions', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'num_extensions')
    op.drop_column('loan', 'allow_extend')
    # ### end Alembic commands ###
