"""empty message

Revision ID: d42cf99ccbe6
Revises: a924c455c0d0
Create Date: 2021-01-31 21:04:28.931772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42cf99ccbe6'
down_revision = 'a924c455c0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_book', 'book', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_book', 'book', ['title', 'author_id'])
    # ### end Alembic commands ###
